// Dionlyonee Jeopardy Official Category & Puzzle Dataset (Vanilla JS)

const JEOPARDY_CATEGORIES = [
  'Countries',
  'Animals',
  'Jamaican / Patwa Phrases',
  'Food',
  'Things You Do',
  'Music',
  'Sports'
];

const JEOPARDY_PUZZLES = {
  'Jamaican / Patwa Phrases': [
    'WAH GWAAN',
    'WEH YUH A SEH',
    'MI DEH YA',
    'EVERYTING IRIE',
    'BIG UP',
    'WALK GOOD',
    'NO PROBLEM',
    'MEK WE GO',
    'YEAH MON',
    'MI SOON COME',
    'WEH DI DEAL',
    'HOW YUH MEAN',
    'MI NUH KNOW',
    'ONE LOVE',
    'BLESS UP',
    'GIVE THANKS',
    'NUFF RESPECT',
    'IRIE VIBES',
    'COME YA',
    'TEK TIME',
    'HOLD A FAITH',
    'MEK IT GO',
    'WHA YUH A DO',
    'HOW TING DEH',
    'MI GOOD',
    'SEEN',
    'FI REAL',
    'NO LIE',
    'WAH FI DO',
    'MEK WE LINK',
    'SMALL UP YUHSELF',
    'PON DI APP',
    'DUTTY WINE',
    'CHULLA VIBES',
    'YAAD MAN',
    'TOUCH DI ROAD',
    'KNOW YUHSELF',
    'LEVEL HEADED'
  ],
  'Countries': [
    'JAMAICA',
    'CANADA',
    'BRAZIL',
    'JAPAN',
    'MEXICO',
    'BAHAMAS',
    'BARBADOS',
    'FRANCE',
    'GERMANY',
    'AUSTRALIA',
    'UNITED STATES',
    'UNITED KINGDOM',
    'SPAIN',
    'ITALY',
    'PORTUGAL',
    'ARGENTINA',
    'TRINIDAD AND TOBAGO',
    'GHANA',
    'NIGERIA',
    'EGYPT',
    'INDIA',
    'CHINA',
    'SOUTH KOREA',
    'IRELAND',
    'GREECE',
    'CUBA',
    'COSTA RICA',
    'COLOMBIA',
    'SOUTH AFRICA',
    'NEW ZEALAND'
  ],
  'Animals': [
    'ELEPHANT',
    'GIRAFFE',
    'MONKEY',
    'DOLPHIN',
    'CROCODILE',
    'KANGAROO',
    'TIGER',
    'GORILLA',
    'PENGUIN',
    'ZEBRA',
    'LION',
    'CHEETAH',
    'LEOPARD',
    'POLAR BEAR',
    'BALD EAGLE',
    'FLAMINGO',
    'PEACOCK',
    'OCTOPUS',
    'BUTTERFLY',
    'CHAMELEON',
    'SEA TURTLE',
    'HUMMINGBIRD',
    'KANGAROO',
    'PANDA BEAR'
  ],
  'Food': [
    'JERK CHICKEN',
    'RICE AND PEAS',
    'ACKEE AND SALTFISH',
    'OXTAIL',
    'ESCOVITCH FISH',
    'BEEF PATTY',
    'COCO BREAD',
    'FESTIVAL',
    'FRIED DUMPLING',
    'BAMMY',
    'CALLALOO',
    'CURRY GOAT',
    'CURRY CHICKEN',
    'PEPPER POT SOUP',
    'PIZZA',
    'HAMBURGER',
    'ICE CREAM',
    'FRIED CHICKEN',
    'MAC AND CHEESE',
    'TACOS',
    'WAFFLES',
    'RED PEA SOUP',
    'STEAMED FISH',
    'JERK PORK'
  ],
  'Things You Do': [
    'WATCH TV',
    'PLAY VIDEO GAMES',
    'GO SHOPPING',
    'GO TO THE BEACH',
    'LISTEN TO MUSIC',
    'TAKE A NAP',
    'BRUSH YOUR TEETH',
    'TAKE A SHOWER',
    'COOK DINNER',
    'GO TO THE GYM',
    'PLAY BASKETBALL',
    'PLAY SOCCER',
    'GO ON VACATION',
    'CLEAN THE HOUSE',
    'DRINK WATER',
    'READ A BOOK',
    'HANG OUT WITH FRIENDS',
    'CALL YOUR FAMILY',
    'TAKE A SELFIE',
    'GO TO A CONCERT'
  ],
  'Music': [
    'REGGAE MUSIC',
    'DANCEHALL MUSIC',
    'HIP HOP',
    'RHYTHM AND BLUES',
    'COUNTRY MUSIC',
    'ROCK AND ROLL',
    'POP MUSIC',
    'GOSPEL MUSIC',
    'JAZZ MUSIC',
    'AFROBEATS',
    'SOCA MUSIC',
    'SOUND SYSTEM',
    'LIVE CONCERT',
    'MUSIC FESTIVAL',
    'DANCE FLOOR',
    'REGGAETON'
  ],
  'Sports': [
    'BASKETBALL',
    'FOOTBALL',
    'SOCCER',
    'BASEBALL',
    'CRICKET',
    'TENNIS',
    'GOLF',
    'VOLLEYBALL',
    'BOXING',
    'WRESTLING',
    'SWIMMING',
    'TRACK AND FIELD',
    'SKATEBOARDING',
    'FORMULA ONE',
    'MARATHON',
    'SURFING',
    'TABLE TENNIS'
  ]
};

const JEOPARDY_HINTS = {
  // Jamaican / Patwa Phrases
  'WAH GWAAN': "Classic greeting: 'What's going on?' / 'How are you?'",
  'WEH YUH A SEH': "Patois greeting: 'What are you saying?' / 'How are things?'",
  'MI DEH YA': "Response meaning 'I am right here' / 'I am doing fine'",
  'EVERYTING IRIE': "Feeling peaceful: 'Everything is alright and peaceful'",
  'BIG UP': "Shoutout or honor: 'Salute and give respect'",
  'WALK GOOD': "Traditional farewell: 'Take care and travel safely'",
  'NO PROBLEM': "Relaxed agreement: 'No worries at all'",
  'MEK WE GO': "Call to action: 'Let us get going / Let's depart'",
  'YEAH MON': "Enthusiastic affirmation: 'Yes definitely / Absolutely'",
  'MI SOON COME': "Classic phrase: 'I will be there in a short while'",
  'WEH DI DEAL': "Inquiry: 'What is the deal / What is happening?'",
  'HOW YUH MEAN': "Strong rhetorical agreement: 'Of course / Obviously!'",
  'MI NUH KNOW': "Uncertainty expression: 'I do not know'",
  'ONE LOVE': "Universal message of unity and peace from Bob Marley",
  'BLESS UP': "Wishing prosperity and positive energy to someone",
  'GIVE THANKS': "Expression of gratitude and appreciation for life",
  'NUFF RESPECT': "Giving massive appreciation: 'Abundant honor & respect'",
  'IRIE VIBES': "Pure positive energy and peaceful good feelings",
  'COME YA': "Direct instruction: 'Come over here'",
  'TEK TIME': "Wise guidance: 'Slow down / Take it easy / Be patient'",
  'HOLD A FAITH': "Encouragement: 'Keep strong and stay faithful'",
  'MEK IT GO': "Advice: 'Let it slide / Don't hold on to anger'",
  'WHA YUH A DO': "Curious question: 'What are you doing?'",
  'HOW TING DEH': "Check-in: 'How are things going with you?'",
  'MI GOOD': "Confirmation: 'I am all good / doing well'",
  'SEEN': "Acknowledgment: 'Understood / I hear you / Got it'",
  'FI REAL': "Affirmation of truth: 'For real / In all honesty'",
  'NO LIE': "Truth teller: 'No exaggeration / That is the honest truth'",
  'WAH FI DO': "Acceptance: 'What is there to do / That's life'",
  'MEK WE LINK': "Invitation: 'Let's meet up and connect'",
  'SMALL UP YUHSELF': "Taxi/bus phrase: 'Make a little room / Scoot over'",
  'PON DI APP': "The official Dionlyonee stream game catchphrase!",
  'DUTTY WINE': "Iconic Jamaican dancehall dance step that went global",
  'CHULLA VIBES': "High energy, hype, and good stream times",
  'YAAD MAN': "Identity: A true native from Jamaica",
  'TOUCH DI ROAD': "Action: Step out into the streets / heading outside",
  'KNOW YUHSELF': "Wisdom: Stay grounded and remember your values",
  'LEVEL HEADED': "Trait: Calm, composed, and balanced",

  // Food
  'JERK CHICKEN': "Signature smoky barbecue with pimento wood & scotch bonnet marinade",
  'RICE AND PEAS': "Quintessential Sunday staple cooked in rich coconut milk & kidney legumes",
  'ACKEE AND SALTFISH': "The national dish of Jamaica paired with preserved Atlantic cod",
  'OXTAIL': "Rich, slow-braised tender cuts with butter beans and savory brown gravy",
  'ESCOVITCH FISH': "Crisp fried whole ocean catch topped with spicy pickled onions & peppers",
  'BEEF PATTY': "Flaky golden turmeric pastry filled with spicy seasoned minced meat",
  'COCO BREAD': "Sweet, fluffy folded bakery loaf made with rich coconut cream",
  'FESTIVAL': "Sweet, crispy golden fried cornmeal fritter often served with fried fish",
  'FRIED DUMPLING': "Hearty golden-brown dough kneaded and fried to crispy perfection",
  'BAMMY': "Traditional disc flatbread made from grated cassava root",
  'CALLALOO': "Nutritious leafy green vegetable sautéed with onions, garlic, and thyme",
  'CURRY GOAT': "Rich, slow-simmered tender meat in fragrant Caribbean turmeric & allspice seasoning",
  'CURRY CHICKEN': "Savory spiced poultry stewed with scotch bonnet, thyme, and yellow turmeric spice",
  'PEPPER POT SOUP': "Traditional thick Caribbean bowl packed with callaloo greens, tubers, and seasoning",
  'RED PEA SOUP': "Hearty, savory broth loaded with kidney legumes, salted beef, and spinners",
  'STEAMED FISH': "Delicate ocean catch poached with okra, water crackers, and natural scotch bonnet",
  'JERK PORK': "Succulent smoky meat charred with pimento leaves and hot scotch bonnet pepper",
  'PIZZA': "Baked crust topped with savory tomato sauce, melted mozzarella, and toppings",
  'HAMBURGER': "Charbroiled patty served inside a toasted sesame bun with condiments",
  'ICE CREAM': "Cold sweet frozen dairy treat churned in various delicious flavors",
  'FRIED CHICKEN': "Crispy, golden-battered seasoned drumsticks & thighs",
  'MAC AND CHEESE': "Comfort food with elbow noodles smothered in sharp cheddar & cream",
  'TACOS': "Folded corn or flour tortilla filled with seasoned meats, cilantro, and onions",
  'WAFFLES': "Crisp griddled batter with deep pocket squares for butter and maple syrup",

  // Countries
  'JAMAICA': "Caribbean island nation renowned for reggae music and world-class sprinters",
  'CANADA': "Northern North American nation famous for maple syrup and hockey",
  'BRAZIL': "South American giant known for Carnival and 5 World Cup championships",
  'JAPAN': "East Asian island nation celebrated for anime, sushi, and bullet trains",
  'MEXICO': "North American country known for mariachi music, tacos, and ancient pyramids",
  'BAHAMAS': "Stunning Caribbean archipelago famous for crystal clear turquoise waters",
  'BARBADOS': "Eastern Caribbean island known as the birthplace of Rihanna",
  'FRANCE': "European nation celebrated for the Eiffel Tower, art, and fine cuisine",
  'GERMANY': "European powerhouse known for the Autobahn, engineering, and castles",
  'AUSTRALIA': "Land Down Under famous for kangaroos, koalas, and the Outback",
  'UNITED STATES': "Nation composed of 50 states spanning coast to coast",
  'UNITED KINGDOM': "Island nation comprising England, Scotland, Wales, and Northern Ireland",
  'SPAIN': "European nation renowned for flamenco, tapas, and sunny beaches",
  'ITALY': "Boot-shaped country famous for pizza, pasta, and the Colosseum",
  'PORTUGAL': "Coastal European country famous for pastel de nata and football legends",
  'ARGENTINA': "South American country known for tango and World Cup soccer glory",
  'TRINIDAD AND TOBAGO': "Twin-island nation renowned for Soca, Calypso, and world Carnival",
  'GHANA': "West African country famous for jollof rice, gold, and rich Ashanti heritage",
  'NIGERIA': "Most populous nation in Africa, powerhouse of Afrobeats and Nollywood",
  'EGYPT': "Ancient civilization home to the Great Pyramids and the Nile River",
  'INDIA': "Vibrant South Asian country known for the Taj Mahal and rich spices",
  'CHINA': "Ancient nation famous for the Great Wall, tea, and pandas",
  'SOUTH KOREA': "East Asian nation famous for K-pop, cutting-edge tech, and kimchi",
  'IRELAND': "The Emerald Isle celebrated for folklore, castles, and St. Patrick's Day",
  'GREECE': "Cradle of Western civilization known for ancient mythology and whitewashed islands",
  'CUBA': "Largest Caribbean island famous for classic cars, salsa music, and cigars",
  'COSTA RICA': "Central American country known for biodiversity, rainforests, and 'Pura Vida'",
  'COLOMBIA': "South American nation famed for premium coffee and vibrant culture",
  'SOUTH AFRICA': "The Rainbow Nation known for wildlife safaris and Table Mountain",
  'NEW ZEALAND': "Island country famous for stunning fjords, kiwi birds, and Maori culture",

  // Animals
  'ELEPHANT': "The largest living land mammal, famous for its long trunk and tusks",
  'GIRAFFE': "The tallest land animal with an exceptionally long neck and patterned coat",
  'MONKEY': "Agile primate known for swinging through tree branches and eating fruit",
  'DOLPHIN': "Highly intelligent marine mammal known for playful acrobatics and clicks",
  'CROCODILE': "Ancient predatory aquatic reptile with powerful jaws and armor-like scales",
  'KANGAROO': "Australian marsupial that hops on powerful hind legs and carries joeys in a pouch",
  'TIGER': "Magnificent apex predator and the largest wild cat with distinctive orange & black stripes",
  'GORILLA': "Gentle giant primate native to the tropical forests of equatorial Africa",
  'PENGUIN': "Flightless aquatic bird wearing a natural 'tuxedo' in icy waters",
  'ZEBRA': "African equines instantly recognizable by their black-and-white striped coats",
  'LION': "The 'King of the Jungle', famous for its majestic mane and thunderous roar",
  'CHEETAH': "The fastest land animal on Earth, capable of reaching 70 mph in short bursts",
  'LEOPARD': "Stealthy spotted big cat known for climbing high trees with heavy prey",
  'POLAR BEAR': "Arctic apex predator with thick white fur adapted for icy landscapes",
  'BALD EAGLE': "Majestic bird of prey known for its white head and piercing eyesight",
  'FLAMINGO': "Graceful wading bird famous for its bright pink feathers and standing on one leg",
  'PEACOCK': "Spectacular male bird known for spreading an enormous iridescent fan of eye-spotted feathers",
  'OCTOPUS': "Eight-armed sea creature with three hearts and unmatched camouflage abilities",
  'BUTTERFLY': "Delicate winged insect that emerges transformed from a caterpillar cocoon",
  'CHAMELEON': "Lizard capable of shifting its skin color and moving its eyes independently",
  'SEA TURTLE': "Ancient ocean wanderer with a hydrodynamic shell and flippers",
  'HUMMINGBIRD': "Tiny bird whose wings flap so fast they create an audible humming buzz",
  'PANDA BEAR': "Beloved bamboo-munching creature native to China with distinct black-and-white patches",

  // Things You Do
  'WATCH TV': "Sitting back on the couch and tuning into your favorite series",
  'PLAY VIDEO GAMES': "Grabbing a controller or keyboard to compete in virtual worlds",
  'GO SHOPPING': "Visiting stores or browsing online to pick up goods and apparel",
  'GO TO THE BEACH': "Relaxing on the warm sand and soaking up the ocean waves",
  'LISTEN TO MUSIC': "Putting on headphones and vibing out to your favorite tracks",
  'TAKE A NAP': "Catching a quick, refreshing 20-minute midday snooze",
  'BRUSH YOUR TEETH': "Daily hygiene routine with a bristled handle, minty foam, and water",
  'TAKE A SHOWER': "Washing off with warm water and soap to start or end the day",
  'COOK DINNER': "Preparing a hot, delicious homemade evening meal in the kitchen",
  'GO TO THE GYM': "Lifting weights and getting a high-energy workout in",
  'PLAY BASKETBALL': "Dribbling, passing, and shooting through a 10-foot hoop on the hardwood",
  'PLAY SOCCER': "Kicking and passing across the grass pitch to score into the net",
  'GO ON VACATION': "Taking time off from work to travel and explore new destinations",
  'CLEAN THE HOUSE': "Sweeping, wiping, and tidying up around your home",
  'DRINK WATER': "Staying hydrated throughout the day with fresh clean fluids",
  'READ A BOOK': "Flipping through printed pages to learn or enjoy a story",
  'HANG OUT WITH FRIENDS': "Spending quality time catching laughs with your close squad",
  'CALL YOUR FAMILY': "Checking in over the phone with loved ones back home",
  'TAKE A SELFIE': "Snapping a quick photo of yourself with your smartphone front camera",
  'GO TO A CONCERT': "Watching your favorite artists perform live on stage with thousands of fans",

  // Music
  'REGGAE MUSIC': "Genre pioneered in Jamaica characterized by heavy basslines and offbeat guitar skanks",
  'DANCEHALL MUSIC': "Energetic, fast-paced Jamaican party genre driven by digital riddims and MC toasts",
  'HIP HOP': "Global urban sound driven by rhythmic 808 beats and lyrical rhyming",
  'RHYTHM AND BLUES': "Soulful genre known for emotive vocal harmonies and melodic grooves",
  'COUNTRY MUSIC': "Acoustic storytelling genre featuring guitars, banjos, and heartfelt lyrics",
  'ROCK AND ROLL': "High-voltage genre powered by distorted electric guitars and driving drum beats",
  'POP MUSIC': "Catchy, chart-topping mainstream radio hits with infectious hooks",
  'GOSPEL MUSIC': "Uplifting spiritual praise songs featuring passionate choir harmonies and worship",
  'JAZZ MUSIC': "Improvisational sound born in New Orleans with complex changes and horn solos",
  'AFROBEATS': "West African movement sweeping the globe with infectious polyrhythms",
  'SOCA MUSIC': "High-speed Carnival rhythm from Trinidad designed for jumping and waving",
  'SOUND SYSTEM': "Tower of booming speakers, turntables, and amplifiers that powers street dances",
  'LIVE CONCERT': "An electric musical performance in front of a live audience",
  'MUSIC FESTIVAL': "Multi-day outdoor gathering with multiple stages and dozens of performing acts",
  'DANCE FLOOR': "The illuminated center stage at a party where everyone comes to move",
  'REGGAETON': "Latin urban genre defined by the syncopated 'dembow' drum rhythm",

  // Sports
  'BASKETBALL': "Fast-paced game where 5 players try to shoot a ball through a 10-foot hoop",
  'FOOTBALL': "Gridiron sport with touchdowns, field goals, and heavy tackles",
  'SOCCER': "The world's most popular game played 11 vs 11 on a grass pitch",
  'BASEBALL': "Diamond-shaped field game involving bats, gloves, 3 strikes, and home runs",
  'CRICKET': "Bat-and-ball game featuring wickets, overs, and centuries popular in the Caribbean",
  'TENNIS': "Racket sport played over a net on grass, clay, or hard courts",
  'GOLF': "Precision club sport where players aim to sink a tiny ball into 18 holes",
  'VOLLEYBALL': "Team sport where players spike and set a ball over a high net without dropping it",
  'BOXING': "Combat discipline where two fighters exchange punches inside a squared ring",
  'WRESTLING': "Grappling sport focused on takedowns, pins, and control",
  'SWIMMING': "Racing through the water using freestyle, butterfly, backstroke, or breaststroke",
  'TRACK AND FIELD': "Athletic competitions including sprints, hurdles, long jump, and relays",
  'SKATEBOARDING': "Riding and performing flip tricks, grinds, and ollies on a wooden deck",
  'FORMULA ONE': "The pinnacle of motorsport racing open-wheel cars at over 200 mph",
  'MARATHON': "Legendary long-distance running race covering 26.2 miles",
  'SURFING': "Riding ocean waves standing on a buoyant fiberglass board",
  'TABLE TENNIS': "Fast-reflex indoor sport played with small paddles and a lightweight hollow ball"
};

// Export to global window scope for direct vanilla browser usage
window.JEOPARDY_CATEGORIES = JEOPARDY_CATEGORIES;
window.JEOPARDY_PUZZLES = JEOPARDY_PUZZLES;
window.JEOPARDY_HINTS = JEOPARDY_HINTS;
